### ISSUE TITLE
Resolve upstream merge conflict

### ISSUE THREAD

**Issue by westhouseit** [kije/gatsby-plugin-offline-next#1]
Hi @kije 

Thanks for your work on this fix. Upstream are ready to rerun the e2e tests, but could do with a fix for some merge conflicts. Any chance you could resolve these or do you need some help?

Thanks,
Paul

**Comment by kije** [comment]
Hi @westhouseit 

I pushed an update to my PR -> see https://github.com/gatsbyjs/gatsby/pull/31542#issuecomment-1114076917
